### ISSUE TITLE
1.2.1.1 changelog oversight

### ISSUE THREAD

**Issue by Michael21107** [sEbi3/Simple-Police-Helper-Menu#1]
> [Note: This update has been published in february 21, 2021.](https://github.com/sEbi3/Simple-Police-Helper/releases/tag/1.2.1.1#:~:text=Note%3A%20This%20update%20has%20been%20published%20in%20february%2021%2C%202021.)

1.2.1.1 was actually released even earlier, on June 28, 2020, [on gta5-mods.com](https://www.gta5-mods.com/scripts/simplepolicehelper-sebi3)

**Comment by sEbi3** [comment]
You're right! I thought I uploaded it on both sites at the same time. It's way too long ago but thanks for letting me know!

**Comment by Michael21107** [comment]
sure thing mate 👍
